# Generated by Django 3.1.7 on 2021-02-19 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materia',
            old_name='Estudiante',
            new_name='estudiante',
        ),
    ]
