# Generated by Django 3.1.7 on 2021-02-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0002_auto_20210219_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='estado',
            field=models.CharField(max_length=50),
        ),
    ]
