# Generated by Django 3.1.7 on 2021-02-23 21:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0003_auto_20210219_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='estudiante',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materia',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AsigMateria',
            fields=[
                ('AsigMateria_id', models.AutoField(primary_key=True, serialize=False)),
                ('estudiante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.estudiante')),
                ('materia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.materia')),
            ],
        ),
    ]
