# Generated by Django 3.1.7 on 2021-02-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0004_auto_20210223_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='estadoCivil',
            field=models.CharField(choices=[('soltero', 'Soltero'), ('casado', 'Casado'), ('divorciado', 'Divorciado'), ('viudo', 'Viudo'), ('separado', 'Separado')], default='soltero', max_length=20),
        ),
    ]
