# Generated by Django 3.1.7 on 2021-02-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0005_auto_20210223_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
    ]
