# Generated by Django 3.1.7 on 2021-02-24 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0007_auto_20210223_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='estudiante',
            new_name='materia',
        ),
    ]
