# Generated by Django 3.1.7 on 2021-02-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0008_auto_20210223_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='estado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nota1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nota2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nota3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='materia',
            name='promedio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
