# Generated by Django 3.1.7 on 2021-02-24 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0011_auto_20210223_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='Estudiante_id',
            new_name='estudiante_id',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='nota1',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='nota2',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='nota3',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='promedio',
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('nota_id', models.AutoField(primary_key=True, serialize=False)),
                ('nota1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nota2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nota3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.estudiante')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.materia')),
            ],
        ),
        migrations.CreateModel(
            name='MateriaEstudiante',
            fields=[
                ('matEst_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.estudiante')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.materia')),
            ],
        ),
    ]
