# Generated by Django 3.1.7 on 2021-02-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0012_auto_20210224_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='estado',
        ),
        migrations.AddField(
            model_name='materiaestudiante',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
